/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emplyeclockinsystem;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Vicsoft
 */
public class AdminReg extends javax.swing.JDialog {

  /**
   * Creates new form Registration
   */
  Connection con;
  Statement st;
  ResultSet rs;
  PreparedStatement ps;
  public String[] rowData;
  Vector<String> data = new Vector<>();
  Vector<String> data2 = new Vector<>();
  String out;
  String newcard;
  byte[] image = null;
  byte print[] = null;
//    int newcard;
  DefaultComboBoxModel combomodel;
  Image im;
//    private DPFPCapture capturer = DPFPGlobal.getCaptureFactory().createCapture();

  public AdminReg(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();

    URL url = this.getClass().getClassLoader().getResource("ThInc.png");
    Image im = Toolkit.getDefaultToolkit().getImage(url);
    setIconImage(im);
    //com();
//        Orga();
    Orga2();
    jButton5.setText("Take Passport");
    jButton9.setVisible(false);
//        if (Main.tab == 1) {
//            jTabbedPane1.setSelectedIndex(2);
//            Main.tab = 0;
//        }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JFormattedTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel43 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox9 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel44 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem4.setText("Change Passport");
        jPopupMenu1.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Registration");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 430, 100, 23);

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(50, 430, 100, 23);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(150, 70, 230, 20);

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(150, 40, 230, 20);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(209, 209, 62), null), "Passport", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BatangChe", 1, 14), new java.awt.Color(209, 209, 62))); // NOI18N

        jLabel42.setToolTipText("employee's Passport");
        jLabel42.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createEtchedBorder()));
        jLayeredPane2.add(jLabel42);

        jPanel1.add(jLayeredPane2);
        jLayeredPane2.setBounds(390, 60, 210, 240);

        jLabel2.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 20);

        jLabel3.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel3.setText("Mobile Number:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 250, 130, 20);

        jLabel11.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel11.setText("SurName:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 40, 100, 20);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(150, 110, 230, 20);

        jButton6.setText("CLOSE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(260, 430, 100, 23);

        jButton7.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(200, 50, 50));
        jButton7.setText("Scan Right Thumb");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(424, 376, 160, 30);

        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 420, 610, 40);

        jLabel4.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 110, 20);

        jLabel5.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel5.setText("Date Of Birth:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 300, 130, 20);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(150, 250, 230, 20);

        jLabel13.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel13.setText("Address:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 370, 130, 20);

        jButton5.setText("Select Passport");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(420, 310, 160, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 350, 230, 60);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(150, 200, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(280, 200, 100, 23);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(150, 150, 230, 20);

        jLabel20.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel20.setText("Gender:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 200, 130, 20);

        jLabel8.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel8.setText("Password:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 150, 110, 20);

        jLabel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null)), "User Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 610, 420);

        jTabbedPane1.addTab("Admin Registration", jPanel1);

        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel12.setText("Username:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 20, 100, 20);

        jLabel18.setFont(new java.awt.Font("BatangChe", 0, 16)); // NOI18N
        jLabel18.setText("Password:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 300, 120, 20);

        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox8);
        jComboBox8.setBounds(130, 20, 230, 20);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(420, 13, 180, 30);

        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 0, 610, 50);

        jLabel14.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel14.setText("Address:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 360, 120, 20);

        jLabel19.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel19.setText("Mobile:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 240, 120, 20);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(130, 360, 230, 90);
        jPanel2.add(jTextField18);
        jTextField18.setBounds(130, 170, 230, 20);

        try {
            jTextField19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jTextField19);
        jTextField19.setBounds(130, 240, 230, 20);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(209, 209, 62), null), "Passport", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BatangChe", 1, 14), new java.awt.Color(209, 209, 62))); // NOI18N
        jLayeredPane3.setToolTipText("");

        jLabel43.setToolTipText("");
        jLabel43.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createEtchedBorder()));
        jLabel43.setComponentPopupMenu(jPopupMenu1);
        jLayeredPane3.add(jLabel43);

        jPanel2.add(jLayeredPane3);
        jLayeredPane3.setBounds(380, 140, 210, 240);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(130, 110, 230, 20);
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(130, 300, 230, 20);

        jLabel24.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel24.setText("Fullname:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 110, 110, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(406, 20, 10, 20);

        jLabel26.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel26.setText("Gender:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 170, 120, 20);

        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null)), "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(0, 50, 610, 410);

        jTabbedPane1.addTab("View/Update Admin", jPanel2);

        jPanel3.setLayout(null);

        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox9);
        jComboBox9.setBounds(260, 20, 250, 20);

        jButton8.setText("Select Passport");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(210, 360, 210, 23);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(209, 209, 62), null), "Update Patient", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BatangChe", 1, 14), new java.awt.Color(209, 209, 62))); // NOI18N
        jLayeredPane4.setToolTipText("click to change image");

        jLabel44.setToolTipText("");
        jLabel44.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createEtchedBorder()));
        jLabel44.setComponentPopupMenu(jPopupMenu1);
        jLayeredPane4.add(jLabel44);

        jButton9.setBackground(java.awt.Color.white);
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/okprint.jpg"))); // NOI18N
        jButton9.setToolTipText("click on the thumb to update employee right thumb");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jLayeredPane4.add(jButton9);

        jPanel3.add(jLayeredPane4);
        jLayeredPane4.setBounds(210, 110, 210, 240);

        jButton11.setText("Update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(210, 410, 210, 23);

        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Update Image");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(160, 60, 120, 30);

        buttonGroup2.add(jCheckBox2);
        jCheckBox2.setText("Update Fingerprint");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2);
        jCheckBox2.setBounds(340, 60, 150, 30);

        jLabel29.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        jPanel3.add(jLabel29);
        jLabel29.setBounds(110, 50, 400, 400);

        jLabel15.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel15.setText("Username:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(110, 20, 100, 20);

        jTabbedPane1.addTab("Update Admin Image and Fingerprint", jPanel3);

        jMenu1.setText("File");

        jMenuItem3.setText("Refresh");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Delete Admin");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    //rand();
    String sex;
    if (jRadioButton1.isSelected()) {
      sex = "Male";
    } else {
      sex = "Female";
    }

    if (jTextField10.getText().isEmpty() || jRadioButton1.getText().isEmpty() || jRadioButton2.getText().isEmpty()
            || jTextField9.getText().isEmpty() || jPasswordField1.getText().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Some Fields Are Empty...\n Recheck All Fields", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
      print = EnrollmentForm.print;
      System.out.println("This is the finger gotten ma broda");

      try {
        LoadDriver();

//                if (print == null || jLabel42.getText().isEmpty()) {
//                    JOptionPane.showMessageDialog(this, "Right thumb finger have not been captured or Passport is Empty", "Error", JOptionPane.ERROR_MESSAGE);
        if (jLabel42.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Passport is Empty", "Error", JOptionPane.ERROR_MESSAGE);
          return;
        } else {
          File f = new File(jLabel42.getText());
          FileInputStream in = new FileInputStream(f);

          image = new byte[(int) f.length()];
          in.read(image);
          if (print != null) {
            in.read(print);
          }
        }
        //  Below: the question marks are IN parameter placeholders.
//                if (f.length() > 60000) {
//                    JOptionPane.showMessageDialog(this, "Cannot capture employee image.", "Passport Error", JOptionPane.WARNING_MESSAGE);
//                    return;
//                }

        String sql = "INSERT INTO admin VALUES(?,?,?,?,?,?,?,?,?,?)";
        ps = con.prepareStatement(sql);
        ps.setInt(1, 0);
        ps.setString(2, jTextField10.getText().toUpperCase() + " " + jTextField9.getText().toUpperCase());
        ps.setString(3, jTextField8.getText());
        ps.setString(4, jPasswordField1.getText());
        ps.setBytes(5, print);
        ps.setBytes(6, image);
        ps.setString(7, sex);
        ps.setString(8, jFormattedTextField1.getText());
        ps.setString(9, jDateChooser1.getDate().getDate() + " " + (jDateChooser1.getDate().getMonth() + 1) + " " + (jDateChooser1.getDate().getYear() + 1900));
        ps.setString(10, jTextArea1.getText());
        JOptionPane.showMessageDialog(this, "User Has Been Registered.\n", "SUCCESSFUL", JOptionPane.INFORMATION_MESSAGE);
        ps.executeUpdate();
        // con.commit();
        System.out.println("you get mouth");
        con.close();
        data.clear();
        Orga2();
                //  enroller.clear();
//                capturer.startCapture();
//                jInternalFrame1.dispose();
//                picture.setIcon(null);
        //     JOptionPane.showMessageDialog(rootPane, jComboBox7.getSelectedItem().toString());
        jButton1ActionPerformed(evt);
        //   }
      } catch (HeadlessException | IOException | SQLException e) {
        System.err.println("I hear Errors " + e);
      }
    }

        //   com();
//        Orga2();
//        Orga();
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jButton7.setEnabled(false);
    jTextField10.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    jPasswordField1.setText("");
    jTextArea1.setText("");
    jFormattedTextField1.setText("");
    jDateChooser1.setDate(null);
    jLabel42.setText("");
    jLabel42.setIcon(null);
    jButton5.setText("Take Passport");
//        Orga();
//        Orga2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
      if (jComboBox8.getSelectedIndex() != 0) {
        //id 	fullname 	position 	sex 	dob 	address 	dp 	bio scan the right thumb	mobileno 	username
        LoadDriver();
        String sql = "update admin set fullname=?,sex=?,mobileno=?,position=?,address=? where username='" + jComboBox8.getSelectedItem().toString() + "'";
        ps = con.prepareStatement(sql);
        ps.setString(1, jTextField11.getText().toUpperCase());
        ps.setString(2, jTextField18.getText().trim());
        ps.setString(3, jTextField19.getText().trim());
        ps.setString(4, jPasswordField2.getText().trim());
        ps.setString(5, jTextArea2.getText());

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successful", "Updated", JOptionPane.INFORMATION_MESSAGE);
        con.commit();
        con.close();

        // com();
//                Orga();
//                Orga2();
        jTextField11.setText("");
        jPasswordField2.setText("");
        jTextField19.setText("");
        jTextField18.setText("");
      } else {
        JOptionPane.showMessageDialog(this, "Select A Valid Company name.", "Company Error", JOptionPane.ERROR_MESSAGE);
      }
    } catch (Exception ex) {
      System.err.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>Yea " + ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    if (jComboBox8.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(this, "Sorry, You Have Not Selected An employee username", "Delete Successful", JOptionPane.INFORMATION_MESSAGE);
    } else {
      int option = JOptionPane.showConfirmDialog(this, "delete " + jComboBox8.getSelectedItem().toString(), "DELETE OPTION", JOptionPane.YES_NO_OPTION);
      if (option == JOptionPane.YES_OPTION) {
        try {
          LoadDriver();
          ps = con.prepareStatement("DELETE FROM `registration` WHERE username ='" + jComboBox8.getSelectedItem().toString() + "'");
          ps.executeUpdate();
          JOptionPane.showMessageDialog(this, "employee Has Been Deleted", "Delete Successful", JOptionPane.INFORMATION_MESSAGE);
          con.close();
          Orga2();
        } catch (SQLException sQLException) {
          System.out.println("error tinx jare ><><><><> " + sQLException);
        }
      } else {
        return;
      }
//            Orga();
      Orga2();
      // com();
      jTextField11.setText("");
      jPasswordField2.setText("");
      jTextField19.setText("");
      jTextField18.setText("");
      jLabel43.setIcon(null);
      jTextArea2.setText("");
    }    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    try {
      setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
      Thread.sleep(400l);
    } catch (Exception e) {
    }
    setCursor(Cursor.getDefaultCursor());
    //com();
//        Orga();
    Orga2();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    FileFilter filter = new FileNameExtensionFilter("JPEG, PNG file", "jpg", "jpeg", "png");
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(filter);
    int result = chooser.showOpenDialog(null);
    if (result == JFileChooser.APPROVE_OPTION) {
      File file = chooser.getSelectedFile();
      try {
        jLabel42.setIcon(new ImageIcon(ImageIO.read(file).getScaledInstance(190, 210, Image.SCALE_AREA_AVERAGING)));
        jLabel42.setText(chooser.getSelectedFile().getPath());
      } catch (IOException ex) {
        Logger.getLogger(AdminReg.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    setCursor(Cursor.getDefaultCursor());

//        jLabel42.setText(chooser.path);
//        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource(jLabel42.getText())));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // enroller.clear();
    // jInternalFrame1.setVisible(true);

    EnrollmentForm form = new EnrollmentForm(new javax.swing.JFrame());
    CaptureForm.log.setText("");
    CaptureForm.hand = 1;
    EnrollmentForm.hand = 1;
    CaptureForm.picture.setIcon(null);
    form.setVisible(true);
    //capturer.startCapture();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
    // capturer.stopCapture();        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
    if (jComboBox8.getSelectedIndex() != 0) {
      connect();
    } else {
      jTextField11.setText("");
      jPasswordField2.setText("");
      jTextField18.setText("");
      jTextField19.setText("");
      jLabel43.setIcon(null);
      jTextArea2.setText("");
      jComboBox8.setSelectedIndex(0);
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    if (jComboBox9.getSelectedIndex() != 0) {

      EnrollmentForm form = new EnrollmentForm(new javax.swing.JFrame());
      CaptureForm.log.setText("");
      EnrollmentForm.hand = 1;
      CaptureForm.hand = 1;
      CaptureForm.picture.setIcon(null);
      form.setVisible(true);
    } else {
      JOptionPane.showMessageDialog(this, "You have not selected employee's username", "Warning", JOptionPane.WARNING_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    if (jComboBox9.getSelectedIndex() != 0) {
      try {
        LoadDriver();
        if (jCheckBox1.isSelected()) {
          File f = new File(jLabel44.getText());
          FileInputStream in = new FileInputStream(f);
          byte[] image = new byte[(int) f.length()];
          in.read(image);
          if (f.length() > 60000) {
            JOptionPane.showMessageDialog(this, "Cannot capture employee image.", "Passport Error", JOptionPane.WARNING_MESSAGE);
            return;
          }
          String sql = "update admin set dp=? where username='" + jComboBox9.getSelectedItem().toString() + "'";
          ps = con.prepareStatement(sql);
          ps.setBytes(1, image);

        } else if (jCheckBox2.isSelected()) {
          print = EnrollmentForm.print;
          String sql = "update admin set bio=? where username='" + jComboBox9.getSelectedItem().toString() + "'";
          ps = con.prepareStatement(sql);
          ps.setBytes(1, print);

        }
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update was Successful", "Updated", JOptionPane.INFORMATION_MESSAGE);
//                con.commit();
        con.close();
        jLabel44.setIcon(null);
        jLabel44.setText("");
        CaptureForm.log.setText("");
        CaptureForm.picture.setIcon(null);
        EnrollmentForm.print = null;
      } catch (IOException | HeadlessException | SQLException f) {
        System.err.println("updating " + f);
      }
    } else {
      JOptionPane.showMessageDialog(this, "You have not selected User's card number", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    jButton9.setVisible(false);
    jLabel44.setVisible(true);
    jButton8.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    jLabel44.setVisible(false);
    jButton8.setVisible(false);
    jButton9.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
//        if (jComboBox9.getSelectedIndex() != 0) {
//        } else {
//            jLabel44.setIcon(null);
//            jLabel44.setText("");
////            jComboBox6.setSelectedIndex(0);
//        }        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
    if (jComboBox9.getSelectedIndex() != 0) {
      FileFilter filter = new FileNameExtensionFilter("JPEG, PNG file", "jpg", "jpeg", "png");
      JFileChooser chooser = new JFileChooser();
      chooser.setFileFilter(filter);
      int result = chooser.showOpenDialog(null);
      if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        try {
          jLabel44.setIcon(new ImageIcon(ImageIO.read(file).getScaledInstance(190, 210, Image.SCALE_AREA_AVERAGING)));
          jLabel44.setText(chooser.getSelectedFile().getPath());
        } catch (IOException ex) {
          Logger.getLogger(AdminReg.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    } else {
      JOptionPane.showMessageDialog(this, "You have not selected an User's username", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    setCursor(Cursor.getDefaultCursor());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

  int i = 2;

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;

        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AdminReg.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AdminReg.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AdminReg.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdminReg.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        AdminReg dialog = new AdminReg(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JFormattedTextField jTextField19;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

  public void LoadDriver() {
    try {
//            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//            con = DriverManager.getConnection("jdbc:odbc:speech");
//            st = con.createStatement();
      String url = "jdbc:mysql://127.0.0.1:3306/employeeatt";
      Class.forName("com.mysql.jdbc.Driver").newInstance();
      // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
      con = DriverManager.getConnection(url, "root", "");
      //  con = DriverManager.getConnection("jdbc:odbc:chat");
      System.err.println("DATABASE CONNECTION ESTABLISHED...\n Remember if u are on the networkor internet change the ip of the system.");
      st = con.createStatement();
    } catch (Exception e) {
      System.out.println("Driver Error " + e);
    }
  }

  private void connect() {
    try {
      System.out.println("Na Wa Oooo " + jComboBox8.getSelectedItem().toString());
      LoadDriver();
      String SQLCommands = "select username from admin";
      rs = st.executeQuery(SQLCommands);
      ResultSetMetaData md = rs.getMetaData();
      int nColumns = md.getColumnCount();
      while (rs.next()) {
        rowData = new String[nColumns];
        for (int i = 0; i < nColumns; i++) {
          rowData[i] = rs.getObject(i + 1).toString();
          data.addElement(rowData[i]);
          System.out.println(" data " + data);

        }
      }
      if (data.contains(jComboBox8.getSelectedItem().toString())) {
        String SQLCommand = "select * from admin WHERE username='" + jComboBox8.getSelectedItem().toString() + "'";
        rs = st.executeQuery(SQLCommand);
        rs.next();
        jTextField11.setText(rs.getString(2));
        jTextField18.setText(rs.getString(7));
        jTextField19.setText(rs.getString(8));
        jPasswordField2.setText(rs.getString(4));
        jTextArea2.setText(rs.getString(10));
        showImage();
      } else {
        jTextField11.setText(null);
        jPasswordField2.setText(null);
        jTextField18.setText(null);
        jTextField19.setText(null);
        jTextArea2.setText(null);
        jLabel43.setIcon(null);
        JOptionPane.showMessageDialog(this, "Select A Valid User UserName", "Error", JOptionPane.ERROR_MESSAGE);
        //  JOptionPane.showMessageDialog(this, "Invalid Credit Card Number", "Error", JOptionPane.WARNING_MESSAGE);
      }
      data.clear();
    } catch (SQLException sQLException) {
      System.err.println("<><><><><><><<<>><><>< " + sQLException);
    }
  }

  private void Orga2() {
    try {
      combomodel = new DefaultComboBoxModel();
      LoadDriver();
      String SQLCommand = "select username from admin ";
      rs = st.executeQuery(SQLCommand);
      ResultSetMetaData md = rs.getMetaData();
      int nColumns = md.getColumnCount();
      combomodel.addElement("Select Username");
      while (rs.next()) {
        rowData = new String[nColumns];
        for (int k = 0; k < nColumns; k++) {
          rowData[k] = rs.getObject(k + 1).toString();
          data.addElement(rowData[k]);
          //combomodel.addElement(data);
          combomodel.addElement(rowData[k]);
          System.out.println();
        }
      }
      jComboBox8.setModel(combomodel);
      jComboBox9.setModel(combomodel);
    } catch (SQLException e) {
      System.out.println("combo box Error" + e);
    } finally {
      try {
        con.close();
      } catch (SQLException ex) {
        Logger.getLogger(AdminReg.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
  }
  int rand = 0;

  void rand() {
    try {
      data2.clear();
      int summ = 1;
      LoadDriver();
      Random random = new Random();
      rand = random.nextInt(9999);
      //  newcard = rand;
      String SQLCommand2 = "select username from registration ";
//            String SQLCommand2 = "select card from member WHERE groupMem='" + jComboBox7.getSelectedItem().toString() + "'";
      rs = st.executeQuery(SQLCommand2);
      ResultSetMetaData md2 = rs.getMetaData();
      int nColumns2 = md2.getColumnCount();
      while (rs.next()) {
        rowData = new String[nColumns2];
        for (int i = 0; i < nColumns2; i++) {
          summ = summ + 1;
          rowData[i] = rs.getObject(i + 1).toString();
          data2.addElement(rowData[i]);
        }
      }
      if (data2.contains("" + rand)) {
        rand();
      }

      con.close();
      data2.clear();
//            JOptionPane.showMessageDialog(this, "employee Card No IS '" + newcard + "'.\n Please keep it safe.", jComboBox7.getSelectedItem().toString(), JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
      System.err.println("Eror kjhsi <><? " + e);
    }
  }

  private void showImage() {
    try {
      LoadDriver();
//            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//            con = DriverManager.getConnection("jdbc:odbc:chat");
//            st = con.createStatement();
      //   System.out.println("image tinx " + jTable2.getValueAt(jTable2.getSelectedRow(), 0));
      String SQLCommand2 = "select dp from admin where username='" + jComboBox8.getSelectedItem().toString() + "'";
      rs = st.executeQuery(SQLCommand2);
      rs.next();
      //    System.err.println("njighbui " + jTable2.getValueAt(jTable2.getSelectedRow(), 3));
      InputStream stream = rs.getBinaryStream(1);
      ByteArrayOutputStream out1 = new ByteArrayOutputStream();
      int a1 = stream.read();
      while (a1 >= 0) {
        out1.write((char) a1);
        a1 = stream.read();
      }
      Image myImage = Toolkit.getDefaultToolkit().createImage(out1.toByteArray());
      Image scaledDaffy
              = myImage.getScaledInstance(190, 210, Image.SCALE_AREA_AVERAGING);//To scale an image
      // jLabel22.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(myImage)));
      jLabel43.setIcon(new javax.swing.ImageIcon(scaledDaffy));
    } catch (Exception g) {
    }
  }

  void updateemployeeSession() {
    try {
      String sql = "INSERT INTO employeesattendance VALUES(?,?,?,?,?,?,?)";
      ps = con.prepareStatement(sql);
      ps.setString(1, "0");
      ps.setString(2, newcard);
      ps.setString(3, jTextField10.getText() + " " + jTextField9.getText() + " " + jTextField8.getText());
      ps.setInt(4, 1);
//            ps.setString(5, jComboBox7.getSelectedItem().toString());
      ps.setString(6, "Registered");
      ps.setString(7, "" + new Date());
      ps.executeUpdate();
    } catch (Exception e) {
      System.out.println("Na Vicsoft do dix stuff " + e);
    }
  }

}
