/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emplyeclockinsystem;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URI;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vicsoft
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    Statement st;
    DefaultComboBoxModel combomodel;
    static String rowData[];
    static Vector<String> data2 = new Vector<String>();
    public static String fullname, user, pw;

    public Login() {
        initComponents();
       
        URL url = this.getClass().getClassLoader().getResource("ThInc.png");
        Image im = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(im);
        jTextField1.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheECS Login");
        setLocationByPlatform(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.add(jTextField1);
        jTextField1.setBounds(190, 130, 260, 30);

        jLabel1.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel1.setText("PASSWORD:");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(60, 220, 100, 30);

        jLabel2.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel2.setText("USERNAME:");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(60, 130, 100, 30);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jDesktopPane1.add(jTextField2);
        jTextField2.setBounds(190, 220, 260, 30);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(200, 300, 100, 30);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(400, 300, 100, 30);

        jButton3.setText("Log In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton3);
        jButton3.setBounds(20, 300, 100, 30);

        jLabel17.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 50)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("EMPLOYEE CLOCKING SYSTEM");
        jDesktopPane1.add(jLabel17);
        jLabel17.setBounds(0, 10, 520, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int y = JOptionPane.showConfirmDialog(this, "Are you sure", "Exit", JOptionPane.YES_NO_OPTION);
        if (y == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Thread.sleep(400l);
        } catch (Exception e) {
        }
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "UserName Or Password Field Is Empty", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                LoadDriver();
                String SQLCommand2 = "select username,pswd from admin";
                rs = st.executeQuery(SQLCommand2);
                ResultSetMetaData md2 = rs.getMetaData();
                int nColumns2 = md2.getColumnCount();
                while (rs.next()) {
                    rowData = new String[nColumns2];
                    for (int i = 0; i < nColumns2; i++) {
                        rowData[i] = rs.getObject(i + 1).toString();
                        data2.addElement(rowData[i]);
                    }
                }
                System.out.println("ok oo <><> " + data2);// && data2.contains(jTextField2.getText())
                if (data2.contains(jTextField1.getText())) {
                    String SQLCommand = "select * from admin WHERE username='" + jTextField1.getText() + "'";
                    rs = st.executeQuery(SQLCommand);
                    rs.next();
                    fullname = rs.getString(2);
                    user = rs.getString(3);
                    pw = rs.getString(4);
                    if (pw.equals(jTextField2.getText())) {
                        System.out.println("Na ur name be dix oo " + fullname + " " + user);
                        JOptionPane.showMessageDialog(this, fullname + ", Welcome User...", "Welcome", JOptionPane.INFORMATION_MESSAGE);
                        jButton1ActionPerformed(evt);
                        dispose();
                        new Main().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Password Not Correct", "LogIn Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "UserName Not Correct", "LogIn Error", JOptionPane.ERROR_MESSAGE);
                }
                // con.commit();
                con.close();
            } catch (Exception g) {
                System.out.print(g);
            }
        }
        setCursor(Cursor.getDefaultCursor());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        jTextField1.requestFocusInWindow();        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButton3ActionPerformed(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jDesktopPane1.getToolkit().beep();
        int y = JOptionPane.showConfirmDialog(this, "Are you sure", "Exit", JOptionPane.YES_NO_OPTION);
        if (y == JOptionPane.YES_OPTION) {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    // End of variables declaration//GEN-END:variables
 public void LoadDriver() {
        try {
//            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//            con = DriverManager.getConnection("jdbc:odbc:speech");
//            st = con.createStatement();
            String url = "jdbc:mysql://127.0.0.1:3306/employeeatt";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection(url, "root", "");
            //  con = DriverManager.getConnection("jdbc:odbc:chat");
            System.err.println("DATABASE CONNECTION ESTABLISHED...\n Remember if u are on the networkor internet change the ip of the system.");
            st = con.createStatement();
        } catch (Exception e) {
            System.out.println("Driver Error " + e);
        }
    }

}
