/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emplyeclockinsystem;

import com.digitalpersona.onetouch.DPFPTemplate;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vicsoft
 */
public class Main extends javax.swing.JFrame {

  /**
   * Creates new form Main
   */
  DefaultTableModel dataSet;
  Connection con;
  Statement st;
  ResultSet rs;
  PreparedStatement ps;
  public static String type;

  public Main() {
    initComponents();

    URL url = this.getClass().getClassLoader().getResource("ThInc.png");
    Image im = Toolkit.getDefaultToolkit().getImage(url);
    setIconImage(im);
    // Center in the screen
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = getSize();
    setLocation(new Point((screenSize.width - frameSize.width) / 2,
            (screenSize.height - frameSize.width) / 50));
    final DateFormat timeFormat = new SimpleDateFormat("EEE, d MMM y HH:mm:ss a");
    ActionListener timerListener = new ActionListener() {
      @Override
      public void actionPerformed(java.awt.event.ActionEvent e) {

        Date date = new Date();
        String time = timeFormat.format(date);
        Time_count.setText(time);
      }
    };
    Timer timer = new Timer(1000, timerListener);
    // to make sure it doesn't wait one second at the start
    timer.setInitialDelay(0);
    timer.start();
    setTableAll();
    setTable3();
    // setTable3();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jButton3 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jButton4 = new javax.swing.JButton();
    jScrollPane4 = new javax.swing.JScrollPane();
    jTable3 = new javax.swing.JTable();
    jLabel3 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem1 = new javax.swing.JMenuItem();
    Time_count = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    jSplitPane1.setDividerLocation(150);
    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

    jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Employee Check In Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BatangChe", 0, 18))); // NOI18N
    jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jScrollPane3MouseClicked(evt);
      }
    });
    jScrollPane3.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jScrollPane3KeyPressed(evt);
      }
    });

    jTable2 = new javax.swing.JTable() {
      public boolean isCellEditable(int row,int colmn) {
        return false;
      }
    };
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {

      }
    ));
    jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable2MouseClicked(evt);
      }
    });
    jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jTable2KeyPressed(evt);
      }
      public void keyReleased(java.awt.event.KeyEvent evt) {
        jTable2KeyReleased(evt);
      }
    });
    jScrollPane3.setViewportView(jTable2);

    jButton3.setText("Print");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jLabel2.setText("Note employing maximum hours of work is 12 hour");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(38, 38, 38)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButton3)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
            .addGap(6, 6, 6)))
        .addGap(0, 3, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Check In Report", jPanel2);

    jButton4.setText("Print");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Employee Check Out Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("BatangChe", 0, 18))); // NOI18N
    jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jScrollPane4MouseClicked(evt);
      }
    });
    jScrollPane4.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jScrollPane4KeyPressed(evt);
      }
    });

    jTable3 = new javax.swing.JTable() {
      public boolean isCellEditable(int row,int colmn) {
        return false;
      }
    };
    jTable3.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {

      }
    ));
    jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable3MouseClicked(evt);
      }
    });
    jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        jTable3KeyPressed(evt);
      }
      public void keyReleased(java.awt.event.KeyEvent evt) {
        jTable3KeyReleased(evt);
      }
    });
    jScrollPane4.setViewportView(jTable3);

    jLabel3.setText("Note employing maximum hours of work is 12 hour");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1032, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(417, 417, 417))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
          .addContainerGap(644, Short.MAX_VALUE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton4)
        .addGap(0, 5, Short.MAX_VALUE))
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
          .addGap(0, 377, Short.MAX_VALUE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    jTabbedPane1.addTab("Check Out Report", jPanel3);

    jSplitPane1.setBottomComponent(jTabbedPane1);

    jPanel1.setLayout(null);

    jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton1.setText("Clock-In");
    jButton1.setToolTipText("get employee right thumb print for Clock in");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);
    jButton1.setBounds(240, 30, 190, 100);
    jButton1.getAccessibleContext().setAccessibleDescription("get employee right thumb print for Clocking in");

    jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton2.setText("Clock-Out");
    jButton2.setToolTipText("get employee right thumb print for Clocking out");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2);
    jButton2.setBounds(569, 30, 190, 100);

    jLabel1.setText("<========>");
    jPanel1.add(jLabel1);
    jLabel1.setBounds(460, 70, 88, 11);

    jSplitPane1.setLeftComponent(jPanel1);

    jMenu1.setText("File");

    jMenuItem2.setText("LogOut");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem3.setText("Exit");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem3);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Registration");

    jMenuItem4.setText("Register Admin");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem4);

    jMenuItem1.setText("Register Employee");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem1);

    jMenuBar1.add(jMenu2);
    jMenuBar1.add(Time_count);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    new employeeReg(new javax.swing.JFrame(), true).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyPressed

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
    if (evt.getKeyCode() == 40) {
      jTable2MouseClicked(null);
    } else if (evt.getKeyCode() == 38) {
      jTable2MouseClicked(null);
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyReleased

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jScrollPane3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane3KeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try {
      //super.print(getGraphics());
      jTable2.print();
    } catch (PrinterException v) {
      System.out.println("printing error signIn " + v);
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try {
      jTable3.print();
    } catch (PrinterException v) {
      System.out.println("printing error signIn " + v);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyPressed

    private void jTable3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyReleased
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyReleased

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void jScrollPane4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane4KeyPressed
    // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4KeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    try {
      setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
      Thread.sleep(400l);
    } catch (InterruptedException e) {
    }
    setCursor(Cursor.getDefaultCursor());
    jPanel1.getToolkit().beep();
    int y = JOptionPane.showConfirmDialog(this, "Are you sure", "Logout", JOptionPane.YES_NO_OPTION);
    if (y == JOptionPane.YES_OPTION) {
      this.dispose();
      new Login().setVisible(true);
    } else {
      setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    type = "signin";
    CaptureForm.log.setText("");
    CaptureForm.picture.setIcon(null);
    VerificationForm f = new VerificationForm(this);
    f.setVisible(true);
    setTable3();
    setTableAll();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    type = "signout";
    CaptureForm.log.setText("");
    CaptureForm.picture.setIcon(null);
    VerificationForm f = new VerificationForm(this);
    f.setVisible(true);
    setTable3();
    setTableAll();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    try {
      setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
      Thread.sleep(400l);
    } catch (InterruptedException e) {
    }
    setCursor(Cursor.getDefaultCursor());
    jPanel1.getToolkit().beep();
    int y = JOptionPane.showConfirmDialog(this, "Are you sure", "Logout", JOptionPane.YES_NO_OPTION);
    if (y == JOptionPane.YES_OPTION) {
      this.dispose();
      System.exit(0);
    } else {
      setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }           // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    new AdminReg(new javax.swing.JFrame(), true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenu Time_count;
  public static javax.swing.JButton jButton1;
  public static javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTabbedPane jTabbedPane1;
  public static javax.swing.JTable jTable2;
  public static javax.swing.JTable jTable3;
  // End of variables declaration//GEN-END:variables
  public static String TEMPLATE_PROPERTY = "template";
  public static DPFPTemplate template;
  public static String cardno, company;

  public DPFPTemplate getTemplate() {
    return template;
  }

  public void setTemplate(DPFPTemplate template) {
    DPFPTemplate old = this.template;
    this.template = template;
    firePropertyChange(TEMPLATE_PROPERTY, old, template);
  }

  public void setTableAll() {
    dataSet = new DefaultTableModel();
    dataSet.addColumn("Fullname");
    dataSet.addColumn("username");
    dataSet.addColumn("Month");
    dataSet.addColumn("TIME-IN");
    dis();
    jTable2.setModel(dataSet);
  }

  public void setTable3() {
    dataSet = new DefaultTableModel();
    dataSet.addColumn("Fullname");
    dataSet.addColumn("username");
    dataSet.addColumn("Month");
    dataSet.addColumn("TIME-IN");
    dataSet.addColumn("TIME-OUT");
    dataSet.addColumn("Duration(hr)");
    dataSet.addColumn("Normal(hr)");
    dataSet.addColumn("Overtime(hr)");
    dis3();
    jTable3.setModel(dataSet);
  }

  private void dis3() {
    try {
      LoadDriver();
//            int row = dataSet.getRowCount();
//            while (row > 0) {
//                row--;
//                dataSet.removeRow(row);
//            }
      //execute query
//            if (jList1.getSelectedValue().toString().equals("ALL")) {
//                rs = st.executeQuery("Select surname,firstname,lastname,card,gender from member ORDER BY card,dateOfRegistration,surname,firstname,lastname");
//
//            } else {
      rs = st.executeQuery("Select fullname,username,month,timeIn,timeOut,duration from report where type='signout' ORDER BY id");
//            }
      //get metadata
      ResultSetMetaData md = rs.getMetaData();
      int colcount = md.getColumnCount() + 2;

      Object[] data = new Object[colcount];
      //extracting data

      while (rs.next()) {
        for (int i = 1; i <= colcount; i++) {
          if (i < colcount - 1) {
            data[i - 1] = rs.getString(i);
          } else if (i == colcount - 1) {
            int j = Integer.parseInt(data[i - 2].toString());
            if (j <= 8) {
              data[i - 1] = j;
            } else {
              data[i - 1] = 8;
            }
          } else {
            System.out.println(data[i - 3].toString());

            int j = Integer.parseInt(data[i - 3].toString());
            if (j <= 8) {
              data[i - 1] = 0;
            } else {
              data[i - 1] = j - 8;
            }
            if ((j - 8) > 4) {
              data[i - 1] = 4;
            }
          }

        }
        dataSet.addRow(data);
      }
      // jLabel1.setText("     " + dataSet.getRowCount());
    } catch (SQLException g) {
      System.out.println(g);
      g.printStackTrace();
    }
  }

  private void dis() {
    try {
      LoadDriver();
      int row = dataSet.getRowCount();
      while (row > 0) {
        row--;
        dataSet.removeRow(row);
      }
      //execute query
//            if (jList1.getSelectedValue().toString().equals("ALL")) {
//                rs = st.executeQuery("Select surname,firstname,lastname,card,gender from member ORDER BY card,dateOfRegistration,surname,firstname,lastname");
//
//            } else {
      rs = st.executeQuery("Select fullname,username,month,timeIn from report ORDER BY id");
//            }
      //get metadata
      ResultSetMetaData md = rs.getMetaData();
      int colcount = md.getColumnCount();

      Object[] data = new Object[colcount];
      //extracting data

      while (rs.next()) {
        for (int i = 1; i <= colcount; i++) {
          data[i - 1] = rs.getString(i);
        }
        dataSet.addRow(data);
      }
      //jLabel1.setText("     " + dataSet.getRowCount());
    } catch (SQLException g) {
      g.printStackTrace();
      System.out.println(g);

    }
  }

  public void LoadDriver() {
    try {
//            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//            con = DriverManager.getConnection("jdbc:odbc:speech");
//            st = con.createStatement();
      String url = "jdbc:mysql://127.0.0.1:3306/employeeatt";
      Class.forName("com.mysql.jdbc.Driver").newInstance();
      // Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
      con = DriverManager.getConnection(url, "root", "");
      //  con = DriverManager.getConnection("jdbc:odbc:chat");
      System.err.println("DATABASE CONNECTION ESTABLISHED...\n Remember if u are on the networkor internet change the ip of the system.");
      st = con.createStatement();
    } catch (Exception e) {
      System.out.println("Driver Error " + e);
    }
  }
}
